### PR TITLE
Adds browser/os notifications on finding a new player

### PR DESCRIPTION
**Pull request by scrangos**
Added functionality to the queue monitor to do a notification at the same time it makes the graceful.mp3 chime.  Also adds an ugly button to enable notifications.  Here's the live version for example https://ashesmatchmakingqueue.infinityfreeapp.com/

### CODE REVIEW

**Comment by warrenkc** [comment]
Thank you.

**Comment by warrenkc** [comment]
@scrangos If you would like to do more such as allow downloads of replays and see match history I have code in C# for that. I can share it with you. I stopped playing Ashes of the Singularity, but I am happy to share what code I had before.

**Comment by scrangos** [comment]
> @scrangos If you would like to do more such as allow downloads of replays and see match history I have code in C# for that. I can share it with you. I stopped playing Ashes of the Singularity, but I am happy to share what code I had before.

Ah, dont think I want to go that far, I just wanted a better alert for when im doing something else and want to see if someone joins the queue :P Figured I'd share it since I had made it already.  But thanks for the offer.

**Comment by warrenkc** [comment]
Ok. Got it.

**Pull request merged**
